services:
  broker:
    image: confluentinc/cp-server:latest  # Use the latest Confluent Kafka image
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"   # Expose the PLAINTEXT listener
      - "9093:9093"   # Expose the CONTROLLER listener
    environment: 
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_CLUSTER_ID: b837ce73-c723-4f6f-9823-367510b6f8ab
    healthcheck: 
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - confluent



networks:
  confluent:
