CREATE DATABASE IF NOT EXISTS SPENZA;

DROP DATABASE IF EXISTS SPENZA;

USE SPENZA;

DROP TABLE IF EXISTS Company;
DROP TABLE IF EXISTS Departments;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Dependants;

CREATE TABLE IF NOT EXISTS Company(
    Company_name CHAR(50) PRIMARY KEY,
    Company_ID INTEGER PRIMARY KEY

);
 
CREATE TABLE IF NOT EXISTS Departments(
    Department_ID VARCHAR(255) PRIMARY KEY,
    Department_name CHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Employees(
    EMPLOYEE_NAME CHAR(255),
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    DEPARTMENT_ID VARCHAR(255) PRIMARY KEY,
    SALARY INTEGER,
	FOREIGN KEY (Department_ID) REFERENCES Departments(Department_ID)
);

CREATE TABLE IF NOT EXISTS Dependants(
    DEPENDANT_NAME CHAR(255),
    DEPENDANT_ID INTEGER,
    RELATIONSHIP CHAR(50),
     FOREIGN KEY (Employee_ID) REFERENCES Employees(Employee_ID)
);

SELECT * FROM Company;
SELECT * FROM Departments;
SELECT * FROM Employees;
SELECT * FROM Dependants;
